version: "3.8"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-football_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ubuntu}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "gunicorn",
        "football.wsgi:application",
        "--bind",
        "0.0.0.0:8000",
        "--workers",
        "3",
      ]
    volumes:
      - .:/app
      - ./media:/app/media
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=football.settings
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
