# Generated by Django 4.2.11 on 2025-09-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_time_ns', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sala',
            new_name='Hall',
        ),
    ]
