# Generated by Django 5.2.6 on 2025-09-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_time_ns', '0002_rename_sala_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='description',
            field=models.TextField(default='Nema opisa'),
        ),
    ]
