# Generated by Django 5.2.6 on 2025-09-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_time_ns', '0003_hall_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='adress',
            new_name='address',
        ),
    ]
