# Generated by Django 5.2.6 on 2025-09-25 09:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_time_ns', '0006_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-start']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 11, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='football_time_ns.hall')),
            ],
            options={
                'ordering': ['hall', 'start'],
            },
        ),
    ]
