# Generated by Django 5.2.6 on 2025-09-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_time_ns', '0007_alter_appointment_options_remove_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='halls/'),
        ),
    ]
