# Generated by Django 5.2.6 on 2025-10-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_time_ns', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner_seen',
            field=models.BooleanField(default=False),
        ),
    ]
