# Generated by Django 5.2.6 on 2025-10-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_time_ns', '0012_review_owner_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_calendar_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
