# Generated by Django 5.2.6 on 2025-10-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_time_ns', '0013_profile_google_calendar_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_auth_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
