# Generated by Django 5.2.6 on 2025-10-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_time_ns', '0014_profile_google_auth_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='google_auth_state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='google_calendar_token',
        ),
    ]
