# Generated by Django 5.2.7 on 2025-10-16 10:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_time_ns', '0015_remove_profile_google_auth_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
