# Generated by Django 5.2.7 on 2025-10-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_time_ns', '0016_hall_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='halls/'),
        ),
        migrations.AlterField(
            model_name='hallimage',
            name='image',
            field=models.FileField(upload_to='halls/'),
        ),
    ]
