# Generated by Django 5.2.7 on 2025-10-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_time_ns', '0017_alter_hall_image_alter_hallimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='halls/'),
        ),
        migrations.AlterField(
            model_name='hallimage',
            name='image',
            field=models.ImageField(upload_to='halls/'),
        ),
    ]
